name: Create artifact [WINDOWS APPX]

on: 
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm i
        
      - name: "Build"
        run: npm run build:appx

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          retention-days: 3
          path: |
            build
            !build/*-unpacked
            !build/.icon-ico
